server:
  port: 8080

spring:
  datasource:
    source:
      jdbc-url: jdbc:mysql://localhost:3306?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    target:
      jdbc-url: jdbc:mysql://localhost:3307?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password  
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.datasync: DEBUG